name: Build and upload debug APK
on:
  push:
    branches:
      "develop"
  pull_request:
    branches:
      "develop"
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK environment
        uses: actions/setup-jave@v1
        with:
          java-version: 11

      - name: Gradle caching
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-key: |
            ${{ runner.os }}-gradle

      - name: Build debug APKs
        run: ./gradlew assembleDebug

      - name: Upload develop debug APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_DEVELOP_DEBUG_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: ${{ github.event.head_commit.message }}
          file: app/build/outputs/apk/develop/debug/app-develop-debug.apk

      - name: Upload production debug APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_PRODUCTION_DEBUG_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: ${{ github.event.head_commit.message }}
          file: app/build/outputs/apk/production/debug/app-production-debug.apk

      - name: Upload develop debug APK to DeployGate
        uses: jmatsu/dg-upload-app-action@v0.2
        with:
          app_owner_name: ${{ secrets.DEPLOYGATE_OWNER_NAME }}
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: app/build/outputs/apk/develop/debug/app-develop-debug.apk